name: Setup and Deploy Filters
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup-and-deploy-filters:
    name: Setup and Deploy Filters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.0"

      - name: Install gmailctl
        run: go install github.com/mbrt/gmailctl/cmd/gmailctl@latest

      - name: Install credentials
        run: |
          mkdir "$HOME/.gmailctl"
          echo "$TOKEN" > "$HOME/.gmailctl/token.json"
          echo "$CREDENTIALS" > "$HOME/.gmailctl/credentials.json"
        env:
          TOKEN: ${{ secrets.GMAILCTL_TOKEN }}
          CREDENTIALS: ${{ secrets.GMAILCTL_CREDENTIALS }}
  
      - name: Update token
        run: gmailctl init --refresh-expired

      - name: Apply changes
        run: gmailctl apply -f main.jsonnet -y