name: Setup and Deploy Filters
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup-and-deploy-filters:
    name: Setup and Deploy Filters
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt update && sudo apt install -y jq

    - name: Install Snapd and GmailCTL
      run: |
        sudo apt update && sudo apt install -y snapd
        sudo snap install gmailctl

    - name: Create configuration files
      run: |
        sudo su
        
        mkdir -p /root/snap/gmailctl/13/.gmailctl
        echo '${{ secrets.GMAILCTL_CREDENTIALS }}' | jq '.' > /root/snap/gmailctl/13/.gmailctl/credentials.json
        echo '${{ secrets.GMAILCTL_TOKEN }}' | jq '.' > /root/snap/gmailctl/13/.gmailctl/token.json

    - name: Init GmailCTL and apply filters
      run: |
        sudo su

        gmailctl init
        gmailctl apply -f filters.jsonnet